# Change these first
owner: ripcdoctor # Your GitHub organization or username, where this repository lives
repo: status_monitor # The name of this repository
user-agent: ripcdoctor
assignees:
  - ripcdoctor
i18n:
  footer: This page is [open source]($REPO), powered by [R.I. PC Doctor](https://ripcdoctor.com)
commitMessages:
  commitAuthorName: "R.I. PC Doctor Status-Bot"
  commitAuthorEmail: "pete@ripcdoctor.com"

sites:
  - name: Web Hosting Services
    url: https://ripcdoctor.com
    maxResponseTime: 500
    expectedStatusCodes:
      - 200
      - 201
      - 403
    icon: https://ripcdoctor.net/favicon.png
  - name: Cloud Hosting Services
    url: https://ripcdoctor.cloud
    maxResponseTime: 2500
    icon: https://ripcdoctor.net/favicon.png
  - name: Short URL Services (ripcdoctor.net/go)
    url: https://ripcdoctor.net/go
    maxResponseTime: 500
    icon: https://ripcdoctor.net/go/images/favicon.svg
  - name: VoIP & Unified Call Management Services
    url: https://peterohara.ddns.net:8089
    maxResponseTime: 500
    __dangerous__insecure: true
    icon: https://ripcdoctor.net/voipfavicon.png
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.ripcdoctor.net
  # baseUrl: /your-repo-name
  logoUrl: https://ripcdoctor.net/logo.png
  name: R.I. PC Doctor Services Status Monitor
  introTitle: "Operational Status of All Services"
  introMessage: Our status page is powered by **R.I. PC Doctor's status-monitor**, the open-source uptime monitor and status page, powered entirely by GitHub. This status page uses **real-time** data from our [GitHub repository](https://github.com/ripcdoctor/status_monitor). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/ripcdoctor/status_monitor).
  navbar:
    - title: Home
      href: https://ripcdoctor.com
    - title: Contact Us
      href: https://ripcdoctor.com/contact
  favicon: https://ripcdoctor.net/favicon.png
  robotsText: "User-agent: * \n Disallow: /"
  theme: ocean

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
