# Change these first
owner: ripcdoctor # Your GitHub organization or username, where this repository lives
repo: status_monitor # The name of this repository

sites:
  - name: Cloud Hosted Services
    url: https://ripcdoctor.cloud
  - name: Web Hosting Services
    url: https://ripcdoctor.com
  - name: Short URL Services (ripcdoctor.net/go)
    url: https://ripcdoctor.net/go
  - name: VoIP & Unified Call Management Services
    url: https://peterohara.ddns.net:8089

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.ripcdoctor.net
  # baseUrl: /your-repo-name
  logoUrl: https://ripcdoctor.com/wp-content/uploads/2021/10/RIPCDoctorLogo.png.webp
  name: R.I. PC Doctor Services Status Monitor
  introTitle: "Our status page is powered by **Upptime**, the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This status page uses **real-time** data from our [GitHub repository](https://github.com/ripcdoctor/status_monitor). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
